#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: Mon Mar 30 09:47:57 PM EDT 2026

pkill -f -9 mpvpaper

for monitor in $(hyprctl monitors -j | jq -r '.[] | .name'); do
    mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5 load-scripts=no" "$monitor" "/home/Justin/Wallpaper/62640.webm" &
    sleep 0.1
done
